package(default_visibility = ["//visibility:public"])

py_library(
    name = "player",
    srcs = [
        "player.py",
    ],
)

py_library(
    name = "game",
    srcs = [ "game.py" ],
)

py_library(
    name = "random_agent",
    srcs = [ "random_agent.py" ],
)
